spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: root
    password: qwerty
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true